# Generated by Django 4.2.11 on 2024-08-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_remove_task_users_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
