# Generated by Django 4.2.11 on 2024-08-03 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
        migrations.AddField(
            model_name='task',
            name='shorten_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
