# Generated by Django 5.0.7 on 2024-08-05 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_remove_task_shorten_link_shortlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortLink',
            new_name='TaskLink',
        ),
        migrations.RenameModel(
            old_name='List',
            new_name='ToDoList',
        ),
    ]
