# Generated by Django 5.0.7 on 2024-08-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0012_alter_todolist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_files'),
        ),
    ]
