# Generated by Django 5.0.7 on 2024-08-18 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0013_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date.today, verbose_name='تاریخ سررسید'),
        ),
    ]
