# Generated by Django 5.0.7 on 2024-08-19 12:43

import datetime
import django.core.validators
import todo_list.models.task
import todo_list.models.task_link
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0014_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date.today, validators=[todo_list.models.task.deadline_validator], verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(600, message='The description must be at least 600 characters long.')], verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_files', validators=[todo_list.models.task.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, validators=[todo_list.models.task.priority_validator], verbose_name='الویت'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, validators=[todo_list.models.task.title_validator, django.core.validators.RegexValidator(code='invalid_title', message='The title can only contain letters, numbers, and spaces.', regex='^[\\w\\s]+$')], verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='tasklink',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, validators=[todo_list.models.task_link.validate_uuid], verbose_name='لینک کوتاه شده'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='The title must be at least 1 characters long.'), django.core.validators.MinLengthValidator(255, message='The title must be at least 255 characters long.'), django.core.validators.RegexValidator(code='invalid_title', message='The title can only contain letters, numbers, and spaces.', regex='^[\\w\\s]+$')], verbose_name='عنوان'),
        ),
    ]
