# Generated by Django 5.0.7 on 2024-08-19 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0015_alter_task_deadline_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(600, message='The description must be at least 600 characters long.')], verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='The title must be at least 1 characters long.'), django.core.validators.MaxLengthValidator(100, message='The title must be at least 255 characters long.'), django.core.validators.RegexValidator(code='invalid_title', message='The title can only contain letters, numbers, and spaces.', regex='^[\\w\\s]+$')], verbose_name='عنوان'),
        ),
    ]
