# Generated by Django 5.0.7 on 2024-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0016_alter_task_description_alter_todolist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.BooleanField(choices=[(True, 'done'), (False, 'undone')], default=False),
        ),
    ]
