# Generated by Django 4.2.11 on 2024-07-30 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='todo_list_app.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
