# Generated by Django 5.0.7 on 2024-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0007_rename_shortlink_tasklink_rename_list_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='ToDoList', to='todo_list_app.task'),
        ),
    ]
